services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager,lambda,s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - type: bind
        source: ./init/ready.d
        target: /etc/localstack/init/ready.d
        read_only: false
      - type: bind
        source: secrets.json
        target: /etc/localstack/init/secrets.json
        read_only: true

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
